/* AMI Type 3 Meter Address Report */

SELECT DISTINCT 
    A.CUSTOMERNUMBER,
    S.PREMISENUMBER,
    S.SERVICEADDRESS,
    A.PREMISEADDRESS2,
    M.DEVICENUMBER
FROM CIS.FCIREGISTER R
JOIN CIS.FCIDEVICE D 
    ON D.CIDVC_DEVICE = R.CIREGISTER_DEVICE
JOIN ENQUESTA.CICUSTOMERMETER M 
    ON M.DEVICENUMBER = R.CIREGISTER_DEVICE
JOIN ENQUESTA.UTELECTRICCUSTOMERMASTER A 
    ON A.CUSTOMERNUMBER = M.CUSTOMERNUMBER
JOIN ENQUESTA.CIPREMISEADDRESS S 
    ON S.PREMISENUMBER = A.PREMISENUMBER
WHERE R.CIREGISTER_CMP_MAKE = 5
  AND D.CIDVC_AMITYPE = 3
  AND A.ACTIVECODE = 0
ORDER BY A.CUSTOMERNUMBER;
